version: '3.8'

services:
  flask-api:
    build: ./flask-api
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx-proxy:
    build: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      flask-api:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
