---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ci-cd-app
data:
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  NGINX_WORKER_PROCESSES: "1"
  NGINX_WORKER_CONNECTIONS: "1024"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ci-cd-app
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # Example: echo -n "your-secret-value" | base64
  API_KEY: ""
  DATABASE_URL: ""
