---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-api-scaler
  namespace: ci-cd-app
spec:
  scaleTargetRef:
    name: flask-api
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
