---
# Prometheus ServiceMonitor for Flask API
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-api-monitor
  namespace: ci-cd-app
spec:
  selector:
    matchLabels:
      app: flask-api
  endpoints:
    - port: 5000
      path: /health
      interval: 30s
---
# Prometheus ServiceMonitor for Nginx
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-proxy-monitor
  namespace: ci-cd-app
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  endpoints:
    - port: 80
      path: /
      interval: 30s
---
# Pod Disruption Budget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flask-api-pdb
  namespace: ci-cd-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: flask-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-proxy-pdb
  namespace: ci-cd-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-proxy
